// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwFupfovecHI63jJWg_hwQtMA0LIA_0BY',
    appId: '1:10934714252:web:1589be97cc4533c32b20a9',
    messagingSenderId: '10934714252',
    projectId: 'todoctodoc-c8702',
    authDomain: 'todoctodoc-c8702.firebaseapp.com',
    storageBucket: 'todoctodoc-c8702.firebasestorage.app',
    measurementId: 'G-9FJS0HWE3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf4lEodn-DNGdG4GzfRiUXiOnWD85f44M',
    appId: '1:10934714252:android:a4e457ffb5c6f7bb2b20a9',
    messagingSenderId: '10934714252',
    projectId: 'todoctodoc-c8702',
    storageBucket: 'todoctodoc-c8702.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8jk-8Cw3PqlbopEAcJtipW1XQsoVK-MU',
    appId: '1:10934714252:ios:1875c5be9afff3702b20a9',
    messagingSenderId: '10934714252',
    projectId: 'todoctodoc-c8702',
    storageBucket: 'todoctodoc-c8702.firebasestorage.app',
    iosBundleId: 'com.practicalproblemsolvers.toDoc.patientVersion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8jk-8Cw3PqlbopEAcJtipW1XQsoVK-MU',
    appId: '1:10934714252:ios:4a1f2b5cc444a0902b20a9',
    messagingSenderId: '10934714252',
    projectId: 'todoctodoc-c8702',
    storageBucket: 'todoctodoc-c8702.firebasestorage.app',
    iosBundleId: 'com.example.toDoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwFupfovecHI63jJWg_hwQtMA0LIA_0BY',
    appId: '1:10934714252:web:38f528422f799cbb2b20a9',
    messagingSenderId: '10934714252',
    projectId: 'todoctodoc-c8702',
    authDomain: 'todoctodoc-c8702.firebaseapp.com',
    storageBucket: 'todoctodoc-c8702.firebasestorage.app',
    measurementId: 'G-M3LK22R4VW',
  );
}
